---
install:
  - SET PATH=C:\Ruby%ruby_version%\bin;%PATH%
  - gem update --system -f
  - gem install bundler -N -f
  - bundle install
build: off
test_script:
  - bundle exec rake test
deploy: off
environment:
  matrix:
    - ruby_version: "25"
    - ruby_version: "25-x64"
    - ruby_version: "26"
    - ruby_version: "26-x64"
    - ruby_version: "27"
    - ruby_version: "27-x64"
